/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gvillena;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.ListModel;

/**
 *
 * @author alumno
 */
public class MainForm extends javax.swing.JFrame {

    ArrayList<TelefonoMovil> ListaTMClaro;
    ArrayList<TelefonoMovil> ListaTMMovistar;
    
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        ListaTMClaro = new ArrayList<TelefonoMovil>();
        ListaTMMovistar = new ArrayList<TelefonoMovil>();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMovistar = new javax.swing.JToggleButton();
        btnClaro = new javax.swing.JToggleButton();
        pblEquiposMovilles = new javax.swing.JScrollPane();
        lstEquiposMoviles = new javax.swing.JList();
        lblTEquiposMoviles = new javax.swing.JLabel();
        lblTCaracteristicas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        plPantalla = new javax.swing.JPanel();
        lblPantalla = new javax.swing.JLabel();
        lblTPantalla = new javax.swing.JLabel();
        plCamara = new javax.swing.JPanel();
        lblCamara = new javax.swing.JLabel();
        lblTCamara = new javax.swing.JLabel();
        plProcesador = new javax.swing.JPanel();
        lblProcesador = new javax.swing.JLabel();
        lblTProcesador = new javax.swing.JLabel();
        btnVerPlanes = new javax.swing.JButton();
        lblDescripcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnMovistar.setText("MOVISTAR");
        btnMovistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovistarActionPerformed(evt);
            }
        });

        btnClaro.setText("CLARO");
        btnClaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaroActionPerformed(evt);
            }
        });

        lstEquiposMoviles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEquiposMovilesValueChanged(evt);
            }
        });
        pblEquiposMovilles.setViewportView(lstEquiposMoviles);

        lblTEquiposMoviles.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTEquiposMoviles.setText("EQUIPOS MOVILES");

        lblTCaracteristicas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTCaracteristicas.setText("CARACTERISTICAS ");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("TIENDA");

        lblPantalla.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblPantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPantalla.setText("--");

        lblTPantalla.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTPantalla.setText("PANTALLA");

        javax.swing.GroupLayout plPantallaLayout = new javax.swing.GroupLayout(plPantalla);
        plPantalla.setLayout(plPantallaLayout);
        plPantallaLayout.setHorizontalGroup(
            plPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plPantallaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(lblTPantalla))
                .addContainerGap())
        );
        plPantallaLayout.setVerticalGroup(
            plPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plPantallaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblPantalla)
                .addGap(30, 30, 30)
                .addComponent(lblTPantalla)
                .addGap(21, 21, 21))
        );

        plCamara.setPreferredSize(new java.awt.Dimension(210, 159));

        lblCamara.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblCamara.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCamara.setText("--");

        lblTCamara.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTCamara.setText("CAMARA");

        javax.swing.GroupLayout plCamaraLayout = new javax.swing.GroupLayout(plCamara);
        plCamara.setLayout(plCamaraLayout);
        plCamaraLayout.setHorizontalGroup(
            plCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plCamaraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCamara, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(lblTCamara))
                .addContainerGap())
        );
        plCamaraLayout.setVerticalGroup(
            plCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plCamaraLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblCamara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lblTCamara)
                .addGap(26, 26, 26))
        );

        lblProcesador.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblProcesador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProcesador.setText("--");

        lblTProcesador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTProcesador.setText("PROCESADOR");

        javax.swing.GroupLayout plProcesadorLayout = new javax.swing.GroupLayout(plProcesador);
        plProcesador.setLayout(plProcesadorLayout);
        plProcesadorLayout.setHorizontalGroup(
            plProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plProcesadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblTProcesador)
                    .addComponent(lblProcesador, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addContainerGap())
        );
        plProcesadorLayout.setVerticalGroup(
            plProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plProcesadorLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(lblProcesador)
                .addGap(29, 29, 29)
                .addComponent(lblTProcesador)
                .addGap(26, 26, 26))
        );

        btnVerPlanes.setText("VER PLANES");

        lblDescripcion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescripcion.setText("***");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pblEquiposMovilles, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTEquiposMoviles))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTCaracteristicas)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(plPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(plCamara, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVerPlanes, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMovistar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClaro, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClaro, btnMovistar});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {plCamara, plProcesador});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMovistar)
                    .addComponent(btnClaro)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTEquiposMoviles)
                    .addComponent(lblTCaracteristicas))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(plCamara, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(plProcesador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(plPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addComponent(btnVerPlanes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(pblEquiposMovilles, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {            
            // Lista Claro 
            Scanner inputClaro = new Scanner(new File("D:\\dataClaro.txt"));
            String lineClaro = "";            
            while (inputClaro.hasNextLine()) {
                lineClaro = inputClaro.nextLine();
                String[] array = lineClaro.split("\t");                
                for (int i = 0; i < array.length; i++) {                    
                    System.out.println(array[i]);            
                }
                ListaTMClaro.add(new TelefonoMovil(array[0], array[1], array[2], array[3]));
            }
            
            // Lista Movistar
            Scanner inputMovistar = new Scanner(new File("D:\\dataMovistar.txt"));
            String lineMovistar = "";            
            while (inputMovistar.hasNextLine()) {
                lineMovistar = inputMovistar.nextLine();
                String[] array = lineMovistar.split("\t");                
                for (int i = 0; i < array.length; i++) {                    
                    System.out.println(array[i]);            
                }
                ListaTMMovistar.add(new TelefonoMovil(array[0], array[1], array[2], array[3]));
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_formWindowOpened

    private void btnMovistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovistarActionPerformed
        System.out.println("CLICK MOVISTAR");        
        btnClaro.setSelected(false);
        lblPantalla.setText("--");
        lblCamara.setText("--");
        lblProcesador.setText("--");
        lblDescripcion.setText("**");
        
        ListModel<String> modelMovistar = new AbstractListModel<String>() {            
                        
            @Override
            public int getSize() { return ListaTMMovistar.size(); }

            @Override
            public String getElementAt(int index) { return ListaTMMovistar.get(index).getDescripcion(); }
        };
        
        lstEquiposMoviles.setModel(modelMovistar);
    }//GEN-LAST:event_btnMovistarActionPerformed

    private void btnClaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaroActionPerformed
        System.out.println("CLICK CLARO");
        btnMovistar.setSelected(false);
        lblPantalla.setText("--");
        lblCamara.setText("--");
        lblProcesador.setText("--");
        lblDescripcion.setText("**");        
        
        ListModel<String> modelClaro = new AbstractListModel<String>() {                        
                        
            @Override
            public int getSize() { return ListaTMClaro.size(); }

            @Override
            public String getElementAt(int index) { return ListaTMClaro.get(index).getDescripcion(); }
        };
        lstEquiposMoviles.setModel(modelClaro);
        
    }//GEN-LAST:event_btnClaroActionPerformed

    private void lstEquiposMovilesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEquiposMovilesValueChanged
        if (!evt.getValueIsAdjusting()) {
            if (btnClaro.isSelected()) {                
                switch (lstEquiposMoviles.getSelectedIndex()) {
                    case 0:
                        System.out.println("CLARO 0");
                        lblPantalla.setText("4.3\"");
                        lblCamara.setText("6MP");
                        lblProcesador.setText("1.3GHz");       
                        lblDescripcion.setText("Galaxy S7 (Claro)");
                        break;
                    case 1:
                        System.out.println("CLARO 1");
                        lblPantalla.setText("6.2\"");
                        lblCamara.setText("8MP");
                        lblProcesador.setText("2.3GHz");                                                
                        lblDescripcion.setText("iPhone 7 (Claro)");
                        break;
                    case 2:
                        System.out.println("CLARO 2");
                        lblPantalla.setText("7.3\"");
                        lblCamara.setText("10MP");
                        lblProcesador.setText("2.7GHz");                                                
                        lblDescripcion.setText("LG k8 (Claro)");
                        break;                    
                }
            }
            else if (btnMovistar.isSelected())
            {
                switch (lstEquiposMoviles.getSelectedIndex()) {
                    case 0:
                        System.out.println("MOVISTAR 0");
                        lblPantalla.setText("6.3\"");
                        lblCamara.setText("5MP");
                        lblProcesador.setText("1.7GHz");                                                
                        lblDescripcion.setText("Galaxy S7 (Movistar)");
                        break;
                    case 1:
                        System.out.println("MOVISTAR 1");
                        lblPantalla.setText("4.3\"");
                        lblCamara.setText("4MP");
                        lblProcesador.setText("2.2GHz");                                                
                        lblDescripcion.setText("iPhone 7 (Movistar)");
                        break;
                    case 2:
                        System.out.println("MOVISTAR 2");
                        lblPantalla.setText("5.1\"");
                        lblCamara.setText("7MP");
                        lblProcesador.setText("1.2GHz");          
                        lblDescripcion.setText("LG k8 (Movistar)");
                        break;                    
                }
            }
        }
        
        
    }//GEN-LAST:event_lstEquiposMovilesValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnClaro;
    private javax.swing.JToggleButton btnMovistar;
    private javax.swing.JButton btnVerPlanes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCamara;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblPantalla;
    private javax.swing.JLabel lblProcesador;
    private javax.swing.JLabel lblTCamara;
    private javax.swing.JLabel lblTCaracteristicas;
    private javax.swing.JLabel lblTEquiposMoviles;
    private javax.swing.JLabel lblTPantalla;
    private javax.swing.JLabel lblTProcesador;
    private javax.swing.JList lstEquiposMoviles;
    private javax.swing.JScrollPane pblEquiposMovilles;
    private javax.swing.JPanel plCamara;
    private javax.swing.JPanel plPantalla;
    private javax.swing.JPanel plProcesador;
    // End of variables declaration//GEN-END:variables
}
